In [1]:
import numpy as np
import pandas as pd

In [20]:
file

'../Bases_de_datos/IRENA/RE_Capacity.csv'

In [45]:
catalog = "../Bases_de_datos/Data_catalog.csv"
df_c = pd.read_csv(catalog)
file = ( "../" + df_c.loc[ df_c["Origin"] == "IRENA", "Path" ].iloc[0]
    + df_c.loc[ df_c["Origin"] == "IRENA", "Filename" ].iloc[0] )
df_re = pd.read_csv(file)

df_re

,CAP (MW),ISO,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,World,-99,1700116.0,1854105.0,2016555.0,2187082.0,2362540.0,2550319.0,2822931.0,3088809.0,3396323.0,3869705.0
1,Africa,-99,32546.0,34813.0,37524.0,42924.0,48264.0,50429.0,53812.0,55665.0,59398.0,62107.0
2,Algeria,DZA,266.0,299.0,499.0,592.0,604.0,604.0,585.0,505.0,590.0,590.0
3,Angola,AGO,1020.0,1020.0,1752.0,2445.0,3113.0,3448.0,3782.0,3782.0,4066.0,4091.0
4,Benin,BEN,1.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,28.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...
229,Peru,PER,4078.0,4711.0,5751.0,5847.0,6123.0,6312.0,6368.0,6431.0,6578.0,6744.0
230,South Georgia,SGS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
231,Suriname,SUR,186.0,188.0,188.0,189.0,190.0,190.0,191.0,191.0,193.0,193.0
232,Uruguay,URY,2441.0,2888.0,3267.0,3711.0,3722.0,3731.0,3735.0,3743.0,3758.0,4089.0
233,Venezuela,VEN,15057.0,15316.0,17007.0,17007.0,17013.0,16978.0,16978.0,17025.0,17025.0,17026.0

In [43]:
df_re.iloc[0, 0].replace(" ", ",")

'World,1,700,116,1,854,105,2,016,555,2,187,082,2,362,540,2,550,319,2,822,931,3,088,809,3,396,323,3,869,705'